title: "Erin E. Tripp"
description: ""
url: "https://eetripp.github.io"
baseurl: ""

# Theme — minima is clean and works out of the box
theme: minima

# Optional: enable extra Jekyll plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap


email: "etripp@hamilton.edu"

header_pages:
- index.md
- research.md
- teaching.md
